### PR TITLE
Splashscreen and App icon added to xcode

### PR DESCRIPTION
**Pull request by NCMoseley**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Hi Nate, your pull request still says "Splashscreen and App icon added to Xcode has no dependencies". Please connect your pull request to dependency (issue) "Splashscreen and App Icon". Thank you!

**Comment by NCMoseley** [comment]
Dependency added. I'm sorry I was aware it should have been added. I guess I am not used to the UI.

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Hi Nate,

please add another dependency saying you added app icons as well or just edit the existing dependency and say add splash screen and app icon

Thank you!

**Comment by NCMoseley** [comment]
Ok!

**Review by siddharthparmar7 — APPROVED** [review]
Nice! thank you, Nate!

**Pull request merged**
