### PR TITLE
Add CompetitionList screen

### PR DESCRIPTION
**Pull request by qingxin-yuan**
Add competitionList component, async query DB method and helpers to handle date object.

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Nice work!

Please remove comments from App.js file. Separate your styling from this file.

Please rename your helper file timestampHelper.js 

Please add propTypes to your CompetitionList.js and CompetitionListContainer file.js

Thank you!

**Comment by qingxin-yuan** [comment]
Hi Sid,
Prop types in componentList added; also delete the styles in app.js (app.js will be deleted eventually, will use index.js instead)

Cheers

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please remove propTypes from CompetitionListContainer.js. Otherwise, it looks good. Nice work!

**Comment by qingxin-yuan** [comment]
Prop types is now removed from the container!

Thanks

**Review by siddharthparmar7 — APPROVED** [review]
Nice! thank you!

**Pull request merged**
