### PR TITLE
Redux set up, async fetching for competitions; tweak some styles.

### PR DESCRIPTION
**Pull request by qingxin-yuan**

### CODE REVIEW

**Review by siddharthparmar7 — APPROVED** [review]
Thank you for making changes!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
You have branch conflicts. Please resolve them

**Comment by qingxin-yuan** [comment]
Conflict fixed!

**Comment by qingxin-yuan** [comment]
Ok, now there's only 1 commit. Please merge this 👾

**Review by siddharthparmar7 — APPROVED** [review]
Thank you!

**Pull request merged**
