### PR TITLE
Add CSS conventions, create Profile UI boilerplate

### PR DESCRIPTION
**Pull request by NCMoseley**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
If you have not implemented Redux right now, do not use react-redux in your ProfileContainer or anywhere else. Do it when you have your Redux store. Remove comments and add propTypes. Thank you!

**Comment by NCMoseley** [comment]
Redux store removed, comments removed, and added propTypes. Thank you!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Nice work Nate! 

I see this message with your pull request "Add CSS conventions, create Profile UI boilerplate has no dependencies". Please add appropriate dependency so I can merge your feature branch to develop branch.

Thank you!

**Comment by NCMoseley** [comment]
That should be better.

**Review by siddharthparmar7 — APPROVED** [review]
great! thank you!

**Pull request merged**
