### PR TITLE
Add Profile Screen styles

### PR DESCRIPTION
**Pull request by NCMoseley**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Please remove all the comments.
Please remove chipStyles from your js/config/styles.js and put it where it belongs (in your chips dir).
Remove propTypes import from Profile.js
Remove comments from ProfileContainer.js
Thank you!

**Comment by NCMoseley** [comment]
Good to go!

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Your App.js file should not be here. Talk to your teammates. They removed it and I don't want you to put it back. (talk to them and do proper rebase)

ProfileContainer.js -> add propTypes

remove comments from Profile/styles.js

**Comment by NCMoseley** [comment]
Ok, it's looking a bit better.

**Comment by NCMoseley** [comment]
Please review this one.

**Comment by NCMoseley** [comment]
Please review this one.

**Review by siddharthparmar7 — COMMENTED** [review]
hey Nate! your brach has conflicts, please resolve them.

**Comment by NCMoseley** [comment]
Please review

**Comment by NCMoseley** [comment]
Sid if you want, merge this branch then we can move the issue to finished. It is finished.

**Pull request closed without merging**
